### ISSUE TITLE
Private helper functions

### ISSUE THREAD

**Issue by skoppe** [dlang-community/stdx-allocator#26]
Most helper functions in stdx-allocator are protected with `package` or with `private`. In order to use them in my own custom allocators I am copying the code into my own module. Besides not liking it, it also produces code bloat in my resulting binaries.

1) I can make pr's to make them publicly available
2) I can submit my own allocators into stdx-allocator (but I would loose fast modification cycle)
3) stop using stdx-allocator and just copy the parts I need

I don't like either option, but am slightly favouring option 1.

**Comment by ghost** [comment]
Yes I remember this when i made tcmallocd and another one. I vote for 1 as well. I think that some of the helper have been moved in other phobos places now (to verify, but must be nextPow2 and like)

**Comment by 9il** [comment]
1

**Comment by ghost** [comment]
@skoppe, vox populi says 1. I  guess you can make a PR.

**Comment by skoppe** [comment]
I will. But first some other stuff.
